# Generated by Django 3.1.1 on 2021-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='select_list',
            field=models.CharField(choices=[('AP', 'Apple'), ('BN', 'Banana'), ('MN', 'Mango'), ('OR', 'Orange')], default='AP', max_length=2),
        ),
    ]
